/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    DesktopLayout: typeof import('./src/components/DesktopLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanTag: typeof import('vant/es')['Tag']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const AppLayout: typeof import('./src/components/AppLayout.vue')['default']
  const DesktopLayout: typeof import('./src/components/DesktopLayout.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanDialog: typeof import('vant/es')['Dialog']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
  const VanForm: typeof import('vant/es')['Form']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanLoading: typeof import('vant/es')['Loading']
  const VanPicker: typeof import('vant/es')['Picker']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanSearch: typeof import('vant/es')['Search']
  const VanSkeleton: typeof import('vant/es')['Skeleton']
  const VanTag: typeof import('vant/es')['Tag']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}